// JavaScript File for solely index.html

// Function for TypeSelector

function openTab(evt, tabName) {
  //fetch all elements with class tab-content and hide
  let tabContent = document.getElementsByClassName("tab-content");
  for (let i = 0; i < tabContent.length; i++) {
      tabContent[i].style.display = "none";
  }

  //fetch all elemeknts with class tab-btn and remove class active
  let tabBtns = document.getElementsByClassName("tab-btn");
  for (let i = 0; i < tabBtns.length; i++) {
      tabBtns[i].className = tabBtns[i].className.replace(" active", "");
  }

  //show current tab, and add an active class btn that opened tab
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " active";
}

//default tab
document.getElementById("section1").style.display = "block";

function helpAlert() {
  alert("Instructions:" + "\n" + "CampusConnect helps you assess and track student engagement in events! \n\nSimply input an individual’s first name, last name, and student ID number. Then, select the date of the event from our handy calendar selector and select the individuals school grade level. Finally, use our section selectors to select an event type and choose your attended event. \n\nHit submit and enjoy seamless entry updating and cloud storage!" +
      " \n\nIn addition, obtain a handy quarterly report automatically generated by CampusConnect or generate random prize winners by pressing the corresponding button!")
}
